# Generated by Django 5.0.14 on 2026-05-11 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('queue_entry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('LEFT_WITHOUT_SEEN', 'Left without being seen')], default='WAITING', max_length=20)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('consult_start_time', models.TimeField(blank=True, null=True)),
                ('consult_end_time', models.TimeField(blank=True, null=True)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('appointment', models.OneToOneField(db_column='appointment_id', on_delete=django.db.models.deletion.PROTECT, related_name='queue_entry', to='appointments.appointment')),
            ],
            options={
                'db_table': 'QUEUE_ENTRY',
                'indexes': [models.Index(fields=['appointment_id'], name='QUEUE_ENTRY_appointment_id_idx')],
            },
        ),
    ]
