# Generated by Django 5.0.14 on 2026-05-11 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_module', '0001_user_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('table_affected', models.CharField(max_length=100)),
                ('record_affected_id', models.BigIntegerField()),
                ('log_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='auth_module.useraccount')),
            ],
            options={
                'db_table': 'AUDIT_LOG',
                'indexes': [models.Index(fields=['log_timestamp'], name='AUDIT_LOG_log_timestamp_idx'), models.Index(fields=['user_id'], name='AUDIT_LOG_user_id_idx')],
            },
        ),
    ]
