# Generated by Django 5.0.14 on 2026-05-11 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0002_department_staff_doctor'),
        ('patients', '0002_medicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(db_column='appointment_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment')),
                ('patient', models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='patients.patient')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='doctors.staff')),
            ],
            options={
                'db_table': 'NOTIFICATION',
                'indexes': [models.Index(fields=['appointment_id'], name='NOTIF_appointment_id_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(check=models.Q(('patient__isnull', False), ('staff__isnull', False), _connector='OR'), name='check_notification_patient_or_staff'),
        ),
    ]
