# Generated by Django 5.0.14 on 2026-05-11 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_department_staff_doctor'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('ADMIN', 'Admin'), ('RECEPTIONIST', 'Receptionist')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=20)),
                ('patient', models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='patients.patient')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='doctors.staff')),
            ],
            options={
                'db_table': 'USER_ACCOUNT',
            },
        ),
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.CheckConstraint(check=models.Q(('patient__isnull', False), ('staff__isnull', False), _connector='OR'), name='USER_ACCOUNT_patient_or_staff_chk'),
        ),
    ]
