# Generated by Django 6.0.5 on 2026-05-17 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queueentry',
            old_name='checked_in_at',
            new_name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='timeslot_id',
        ),
        migrations.RemoveField(
            model_name='queueentry',
            name='called_at',
        ),
        migrations.RemoveField(
            model_name='queueentry',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='queueentry',
            name='queue_number',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default='2026-01-01'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='qr_code_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('in-person', 'In Person'), ('online', 'Online')], default='in-person', max_length=20),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='patient_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='patient_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='student_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('LEFT_WITHOUT_SEEN', 'Left Without Seen')], default='WAITING', max_length=20),
        ),
    ]
