# Generated by Django 5.0.14 on 2026-05-11 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("student_number", models.CharField(max_length=10, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contact_number", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField()),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=10)),
                ("consent_given", models.BooleanField(default=False)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "PATIENT",
            },
        ),
        migrations.CreateModel(
            name="PatientContact",
            fields=[
                ("patient_contact_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("contact_name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=20)),
                ("relationship", models.CharField(blank=True, max_length=100)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "PATIENT_CONTACT",
            },
        ),
    ]
