# Generated by Django 5.0.14 on 2026-05-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('slot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'TIMESLOT',
                'indexes': [models.Index(fields=['slot_date'], name='TIMESLOT_slot_date_idx'), models.Index(fields=['slot_date', 'is_available'], name='TIMESLOT_slot_date_avail_idx')],
            },
        ),
    ]
