# Generated by Django 5.0.14 on 2026-05-11 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'DEPARTMENT',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('ADMIN', 'Admin')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('working_hours_start', models.TimeField()),
                ('working_hours_end', models.TimeField()),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='doctors.department')),
            ],
            options={
                'db_table': 'STAFF',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('staff', models.OneToOneField(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_profile', serialize=False, to='doctors.staff')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('specialisation', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'DOCTOR',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head_staff',
            field=models.ForeignKey(blank=True, db_column='head_staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='doctors.staff'),
        ),
    ]
